'use client';

import {useEffect,useRef,useState} from 'react';
import {ArrowUpRight,ArrowRight,ArrowDown,Check,Copy,ExternalLink,RefreshCw,Wallet,X,ChevronRight,ShieldCheck,Info,LoaderCircle,ReceiptText,Search} from 'lucide-react';
import {Slider} from '@/components/ui/slider';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Checkbox} from '@/components/ui/checkbox';
import {type Stock,type Preview,company,money,compact,percent} from '@/lib/market';
import {displayTokenAmount} from '@/lib/token-units';

type Provider={publicKey?:{toString():string};connect:()=>Promise<{publicKey:{toString():string}}>;signTransaction:(tx:any)=>Promise<any>;on?:(e:string,cb:(key:any)=>void)=>void;removeListener?:(e:string,cb:(key:any)=>void)=>void};
declare global {interface Window{phantom?:{solana:Provider};solana?:Provider;solflare?:Provider;}}
type Receipt={signature:string;symbol:string;amount:number;tokens:number;entryPrice:number;time:string};
const sectors:Record<string,string>={OPENAI:'Artificial intelligence',ANTHROPIC:'Artificial intelligence',SPACEX:'Space & connectivity',ANDURIL:'Defense technology',FIGUREAI:'Robotics',KALSHI:'Prediction markets',POLYMARKET:'Prediction markets',NEURALINK:'Brain interfaces'};
const short=(s:string)=>s.slice(0,4)+'…'+s.slice(-4);
async function api(url:string,init?:RequestInit){const r=await fetch(url,init);const d:any=await r.json();if(!r.ok||d.error)throw new Error(d.error||'Request failed. Please retry.');return d;}
function Logo({stock,large=false}:{stock:Stock;large?:boolean}){return <span className={'company-logo '+(large?'large':'')}><img src={stock.image} alt="" onError={e=>{e.currentTarget.style.display='none'}}/><span>{company(stock).slice(0,2)}</span></span>}

export default function Home(){
 const [stocks,setStocks]=useState<Stock[]>([]),[selected,setSelected]=useState('OPENAI'),[catalogTime,setCatalogTime]=useState(''),[catalogError,setCatalogError]=useState(''),[search,setSearch]=useState('');
 const [amount,setAmount]=useState(100),[draft,setDraft]=useState('100'),[quote,setQuote]=useState<Preview|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState(''),[refresh,setRefresh]=useState(0),[now,setNow]=useState(Date.now());
 const [wallet,setWallet]=useState(''),[walletOpen,setWalletOpen]=useState(false),[walletError,setWalletError]=useState(''),[connecting,setConnecting]=useState(false),[review,setReview]=useState(false),[eligible,setEligible]=useState(false),[trading,setTrading]=useState(false),[receipt,setReceipt]=useState<Receipt|null>(null),[receiptOpen,setReceiptOpen]=useState(false),[copied,setCopied]=useState(false);
 const provider=useRef<Provider|null>(null),requestId=useRef(0);
 const stock=stocks.find(s=>s.symbol===selected)||stocks[0];
 async function loadCatalog(){setCatalogError('');try{const data=await api('/api/catalog');setStocks(data.stocks);setCatalogTime(data.fetchedAt);}catch(e){setCatalogError((e as Error).message);}}
 useEffect(()=>{loadCatalog();const timer=setInterval(()=>setNow(Date.now()),1000);return()=>clearInterval(timer)},[]);
 useEffect(()=>{if(!stock)return;const id=++requestId.current;const controller=new AbortController();setQuote(null);setError('');setLoading(true);setReview(false);setEligible(false);const timer=setTimeout(async()=>{try{const data=await api('/api/quote?'+new URLSearchParams({mint:stock.contract_address,amount:String(amount),...(wallet?{taker:wallet}:{})}),{signal:controller.signal});if(id===requestId.current){setQuote(data);setStocks(previous=>previous.map(s=>s.contract_address===data.stock.contract_address?data.stock:s));setCatalogTime(data.catalogFetchedAt);}}catch(e){if(id===requestId.current&&!controller.signal.aborted)setError((e as Error).message);}finally{if(id===requestId.current)setLoading(false)}},700);return()=>{clearTimeout(timer);controller.abort()}},[stock?.contract_address,amount,refresh,wallet]);
 useEffect(()=>{const p=provider.current;if(!p)return;const changed=(key:any)=>{setWallet(key?.toString()||'');setReview(false);setEligible(false)};const disconnected=()=>changed(null);p.on?.('accountChanged',changed);p.on?.('disconnect',disconnected);return()=>{p.removeListener?.('accountChanged',changed);p.removeListener?.('disconnect',disconnected)}},[wallet]);
 const age=quote?Math.max(0,Math.floor((now-new Date(quote.quotedAt).getTime())/1000)):0;
 const stale=age>30||!!(quote?.multiplierValidUntil&&now>=quote.multiplierValidUntil);
 const validAmount=Number(draft)>=1&&Number(draft)<=10000&&Math.abs(Number(draft)-amount)<0.000001;
 const catalogPremium=stock?(stock.tokenPrice/stock.markPrice-1)*100:0;
 const entryRatio=quote?quote.entryValuation/quote.stock.markValuation:stock?stock.impliedValuation/stock.markValuation:1;
 const maxRatio=Math.max(1,entryRatio)*1.15;
 function changeAmount(n:number){const value=Math.min(10000,Math.max(1,Math.round(n*100)/100));setAmount(value);setDraft(String(value));}
 async function connect(kind:'phantom'|'solflare'){
  const p=kind==='phantom'?window.phantom?.solana:window.solflare;setWalletError('');if(!p){setWalletError(`Open Before in a browser with ${kind==='phantom'?'Phantom':'Solflare'} installed, or in the wallet’s browser.`);return;}setConnecting(true);try{const result=await p.connect();provider.current=p;setWallet(result.publicKey.toString());setWalletOpen(false);}catch(e){setWalletError((e as Error).message||'Wallet connection was cancelled.')}finally{setConnecting(false)}
 }
 async function trade(){
  if(!quote||!provider.current||!wallet||!eligible||stale||!validAmount||!quote.buy.transaction)return;
  setTrading(true);setError('');try{
   if(provider.current.publicKey?.toString()!==wallet)throw new Error('Wallet changed. Reconnect and refresh your quote.');
   const {VersionedTransaction}=await import('@solana/web3.js');
   const tx=VersionedTransaction.deserialize(Uint8Array.from(atob(quote.buy.transaction),c=>c.charCodeAt(0)));
   const signed=await provider.current.signTransaction(tx);
   const data=await api('/api/execute',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({signedTransaction:btoa(String.fromCharCode(...signed.serialize())),requestId:quote.buy.requestId})});
   if(data.status!=='Success')throw new Error(data.error||'The transaction was not confirmed. Check your wallet before retrying.');
   const input=Number(data.totalInputAmount||data.inputAmountResult)/1e6,output=displayTokenAmount(String(data.totalOutputAmount||data.outputAmountResult),quote.decimals,quote.uiMultiplier);
   if(!data.signature)throw new Error('Execution returned no signature. Check your wallet before retrying.');
   setReceipt({signature:data.signature,symbol:quote.stock.symbol,amount:input,tokens:output,entryPrice:input/output,time:new Date().toISOString()});setReview(false);setReceiptOpen(true);setQuote(null);setRefresh(x=>x+1);
  }catch(e){setError((e as Error).message);}finally{setTrading(false)}
 }
 async function share(){if(!receipt)return;const text=`Before · ${receipt.symbol}\nSpent ${receipt.amount.toFixed(6)} USDC · Received ${receipt.tokens} tokens\nEntry price ${money(receipt.entryPrice)} USDC/token\n${receipt.time}\nhttps://solscan.io/tx/${receipt.signature}`;try{await navigator.clipboard.writeText(text);setCopied(true);setTimeout(()=>setCopied(false),2000)}catch{setError('Clipboard unavailable. Use the transaction link to share your receipt.')}}
 return <div className="app-shell">
  <header className="topbar"><a className="brand" href="/" aria-label="Before home"><span className="brand-mark">b<span>↗</span></span>before<span className="brand-period">.</span></a><div className="top-context">PRIVATE COMPANIES. <span>PUBLIC CLARITY.</span></div><div className="header-actions"><span className="network"><span className="solana-bars">≋</span> Solana</span><button className="wallet-button" onClick={()=>setWalletOpen(true)}><Wallet size={16}/>{wallet?short(wallet):'Connect wallet'}</button></div></header>
  <div className="workspace">
   <aside className="market-panel"><div className="panel-heading"><span>THE WATCHLIST</span><span className="count">{stocks.length||'—'}</span></div><h1>Before the IPO.</h1><p className="muted">Find your next conviction.</p><label className="search"><Search size={16}/><input aria-label="Find a company" placeholder="Find a company" value={search} onChange={e=>setSearch(e.target.value)}/>{search&&<button aria-label="Clear search" onClick={()=>setSearch('')}><X size={14}/></button>}</label>
    <div className="company-list">{stocks.filter(s=>(s.name+' '+s.symbol).toLowerCase().includes(search.toLowerCase())).map(s=><button key={s.symbol} className={'company-button '+(stock?.symbol===s.symbol?'selected':'')} onClick={()=>{setSelected(s.symbol);setSearch('')}}><Logo stock={s}/><span className="company-label"><strong>{company(s)}</strong><small>{sectors[s.symbol]||'Private company'}</small></span><ChevronRight size={16}/></button>)}{stocks.length>0&&!stocks.some(s=>(s.name+' '+s.symbol).toLowerCase().includes(search.toLowerCase()))&&<p className="empty">No companies match “{search}”.</p>}{!stocks.length&&!catalogError&&<div className="empty"><LoaderCircle className="spin" size={20}/>Loading PreStocks…</div>}{catalogError&&<div className="error-box">{catalogError}<button onClick={loadCatalog}>Try again</button></div>}</div>
    <div className="sidebar-foot"><ShieldCheck size={18}/><div><strong>Exclusively PreStocks</strong><p>Verified token addresses.<br/>Straight from the issuer.</p></div></div><a className="subtle-link" href="https://prestocks.com/products" target="_blank" rel="noreferrer">Explore the issuer <ArrowUpRight size={14}/></a>
   </aside>
   <main>{stock?<><div className="breadcrumb">Discover <ChevronRight size={13}/> {company(stock)} <span className="data-label">PreStocks catalog · {catalogTime?new Date(catalogTime).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'}):'loading'}</span></div>
    <section className="company-intro"><div className="company-title"><Logo stock={stock} large/><div><div className="eyebrow">{sectors[stock.symbol]||'PRE-IPO COMPANY'}</div><h2>{company(stock)} <span>{stock.symbol}</span></h2></div></div><a className="issuer-link" href={stock.external_url} target="_blank" rel="noreferrer">Company on PreStocks <ArrowUpRight size={16}/></a></section>
    <p className="description">{stock.description.split('\n')[0]}</p>
    <div className="overview"><div><span>Catalog token price</span><strong>{money(stock.tokenPrice)}</strong></div><div><span>Implied company valuation</span><strong>{compact(stock.impliedValuation)}</strong></div><div><span>Premium to reference mark</span><strong className={catalogPremium>0?'amber':'mint'}>{percent(catalogPremium)} <small>{catalogPremium>0?'ABOVE':'BELOW'} MARK</small></strong></div></div>
    <section className="trade-workspace"><div className="section-heading"><div><span className="eyebrow">THE REAL COST</span><h3>Know your way in. And out.</h3></div><span className="live-label">{loading?<LoaderCircle size={13} className="spin"/>:<span className={'status-dot '+(quote&&!stale?'active':'')}/>} {loading?'Finding routes':quote?(stale?'Quote expired':`Quoted ${age}s ago`):'Awaiting quote'}</span></div>
     <div className="trade-grid"><div className="amount-panel"><label htmlFor="investment">I want to invest</label><div className="amount-input"><span>$</span><input id="investment" type="number" min="1" max="10000" step="0.01" value={draft} onChange={e=>{setDraft(e.target.value);const n=Number(e.target.value);if(n>=1&&n<=10000&&Number.isFinite(n))setAmount(Math.round(n*100)/100)}} onBlur={()=>changeAmount(Number(draft)||100)}/><span className="currency">USDC</span></div><div className="presets">{[100,500,1000,5000].map(n=><button className={amount===n?'chosen':''} onClick={()=>changeAmount(n)} key={n}>${n.toLocaleString()}</button>)}</div><Slider aria-label="Investment amount in USDC" min={1} max={10000} step={1} value={[amount]} onValueChange={v=>changeAmount(v[0])}/><div className="range-labels"><span>$1</span><span>$10,000</span></div><div className="route-note"><ShieldCheck size={16}/><p>Quotes use the exact token amount you’d receive. No simulated liquidity.</p></div></div>
     <div className="outcome-panel" aria-live="polite"><div className="outcome-row"><span className="step-number">01</span><div><span>You buy</span><strong>{quote?quote.tokens.toLocaleString('en-US',{maximumFractionDigits:6}):'—'} <small>{stock.symbol}</small></strong></div><ArrowDown size={20}/></div><div className="journey-line"><span>Then request an immediate sell quote</span></div><div className="outcome-row"><span className="step-number exit">02</span><div><span>You could receive back</span><strong className="exit-value">{quote?money(quote.exitUsdc):'—'} <small>USDC</small></strong></div></div><div className="roundtrip"><span>Round-trip difference <Info size={13}/></span><strong>{quote?`${quote.roundTrip>=0?'−':'+'}${money(Math.abs(quote.roundTrip))} (${(Math.abs(quote.roundTrip)/quote.amount*100).toFixed(2)}%)`:'—'}</strong></div><p className="fineprint">Independent quotes at current liquidity. USDC is shown at $1 parity. The sell quote does not model the pool changes your buy would cause. Quotes include route fees; network fees are additional.</p></div></div>
     {error&&<div role="alert" className="error-box">{error}<button onClick={()=>setRefresh(x=>x+1)}>Retry quote</button></div>}
     <div className="trade-bottom"><div><Info size={16}/><span>{quote?`Effective entry: ${money(quote.entryPrice)} USDC per token`:'Choose an amount to compare executable prices.'}</span></div><div className="trade-actions"><button className="icon-button" disabled={loading||trading} onClick={()=>setRefresh(x=>x+1)} aria-label="Refresh quote"><RefreshCw size={17} className={loading?'spin':''}/></button><button className="primary-button" disabled={loading||!quote||trading||!validAmount} onClick={()=>{if(!wallet)setWalletOpen(true);else if(stale)setRefresh(x=>x+1);else setReview(true)}}>{loading?'Getting your quote':!wallet?'Connect to review':stale?'Refresh to review':'Review purchase'}{loading?<LoaderCircle size={16} className="spin"/>:<ArrowRight size={17}/>}</button></div></div>
    </section>
    <div className="insights-grid"><section className="valuation-card"><div className="card-title"><h3>The valuation behind your price</h3><span className="mini-tag">CONTEXT</span></div><p className="muted">Your entry price, expressed as a company valuation.</p><div className="valuation-bar"><div><span>Provider reference mark</span><strong>{compact(stock.markValuation)}</strong></div><div className="bar-track"><span style={{width:`${100/maxRatio}%`}}/></div></div><div className="valuation-bar entry"><div><span>{quote?'Your quoted entry':'Catalog implied valuation'}</span><strong>{compact(quote?quote.entryValuation:stock.impliedValuation)}</strong></div><div className="bar-track"><span style={{width:`${entryRatio/maxRatio*100}%`}}/></div></div><p className="valuation-summary"><span className={(quote?quote.premium:catalogPremium)>0?'amber':'mint'}>{percent(quote?quote.premium:catalogPremium)}</span> against the provider’s mark. A reference point, not a fair-value estimate.</p><p className="fineprint">Mark effective date is not supplied by PreStocks. Catalog retrieval time is shown above. Token amounts account for the issuer’s display adjustments. Derived entry valuation assumes the same token-to-company valuation ratio as the provider.</p></section>
    <section className="details-card"><div className="card-title"><h3>Look under the hood</h3><ArrowUpRight size={17}/></div><dl><div><dt>Issued by</dt><dd>PreStocks <ShieldCheck size={13}/></dd></div><div><dt>Buy route</dt><dd>{quote?Array.from(new Set(quote.buy.routePlan?.map(r=>r.swapInfo.label)||[quote.buy.router])).join(' → '):'—'}</dd></div><div><dt>Entry vs catalog</dt><dd>{quote?percent((quote.entryPrice/quote.stock.tokenPrice-1)*100):'—'}</dd></div><div><dt>Buy platform fee</dt><dd>{quote?(quote.buy.feeBps/100).toFixed(2)+'% · in quote':'—'}</dd></div><div><dt>Quote network costs</dt><dd>{quote&&wallet?((Number(quote.buy.signatureFeeLamports||0)+Number(quote.buy.prioritizationFeeLamports||0)+Number(quote.buy.rentFeeLamports||0))/1e9).toFixed(6)+' SOL':'Connect wallet to estimate'}</dd></div><div><dt>Token contract</dt><dd><a href={'https://solscan.io/token/'+stock.contract_address} target="_blank" rel="noreferrer">{short(stock.contract_address)} <ExternalLink size={12}/></a></dd></div></dl></section></div>
    <footer><p>Economic exposure to private companies, not direct equity ownership. No voting or dividend rights. Liquidity is not guaranteed. PreStocks excludes U.S. persons and other ineligible users.</p><div><span>Built on Solana. Powered by PreStocks + Jupiter.</span><a href="https://prestocks.com/faq" target="_blank" rel="noreferrer">Understand the risks <ArrowUpRight size={13}/></a></div></footer>
   </>:<div className="loading-main"><span className="brand-mark">b<span>↗</span></span><h2>Your next investment deserves clarity.</h2><p>{catalogError?'Market data is unavailable. Use “Try again” to reconnect.':'Connecting to the PreStocks catalog…'}</p></div>}</main>
  </div>
  <Dialog open={walletOpen} onOpenChange={setWalletOpen}><DialogContent className="before-dialog"><DialogTitle>{wallet?'Your wallet':'Connect your wallet'}</DialogTitle><DialogDescription>Connect a Solana wallet to review a purchase. Every transaction requires your signature.</DialogDescription>{wallet?<><p className="wallet-address">{wallet}</p><button className="secondary-button" onClick={()=>{setWallet('');provider.current=null;setWalletOpen(false)}}>Disconnect from Before</button></>:<><button className="wallet-option" disabled={connecting} onClick={()=>connect('phantom')}><Wallet/>Phantom <ArrowRight size={17}/></button><button className="wallet-option" disabled={connecting} onClick={()=>connect('solflare')}><Wallet/>Solflare <ArrowRight size={17}/></button></>}{walletError&&<p className="error-box" role="alert">{walletError}</p>}<p className="fineprint">Before never requests your seed phrase or private keys.</p></DialogContent></Dialog>
  <Dialog open={review} onOpenChange={v=>{if(!trading)setReview(v)}}><DialogContent className="before-dialog"><DialogTitle>Review your purchase</DialogTitle><DialogDescription>Solana mainnet · Real USDC · {wallet?short(wallet):''}</DialogDescription>{quote&&<><div className="review-amount">{money(quote.amount)} <span>USDC → {quote.stock.symbol}</span></div><dl className="review-details"><div><dt>Quoted tokens received</dt><dd>{quote.tokens.toFixed(6)}</dd></div><div><dt>Effective entry / token</dt><dd>{money(quote.entryPrice)}</dd></div><div><dt>Immediate exit quote</dt><dd>{money(quote.exitUsdc)} USDC</dd></div><div><dt>Quote age</dt><dd>{age}s {stale?'· Refresh required':''}</dd></div></dl><p className="fineprint">Execution can differ from this quote. Review the amounts and fees in your wallet. The exit quote is indicative and does not guarantee future liquidity.</p><label className="eligibility"><Checkbox checked={eligible} onCheckedChange={v=>setEligible(v===true)}/><span>I am eligible under <a href="https://prestocks.com/faq" target="_blank" rel="noreferrer">PreStocks’ restrictions</a>, am not a U.S. person, and understand these tokens do not confer shareholder rights.</span></label>{error&&<p className="error-box" role="alert">{error}</p>}{!quote.buy.transaction&&<p className="error-box">{quote.buy.errorMessage||'The provider could not prepare a transaction for this wallet.'} You can still compare prices. Purchasing requires sufficient USDC and any required SOL network fees. Refresh after changing your balance.</p>}<button className="primary-button full" disabled={trading||(!stale&&(!eligible||!quote.buy.transaction))} onClick={()=>stale?setRefresh(x=>x+1):trade()}>{trading?'Waiting for wallet & confirmation…':stale?'Refresh quote':'Approve in wallet'}{trading?<LoaderCircle className="spin" size={17}/>:<ArrowRight size={17}/>}</button></>}</DialogContent></Dialog>
  <Dialog open={receiptOpen} onOpenChange={setReceiptOpen}><DialogContent className="before-dialog receipt"><div className="success-icon"><Check/></div><DialogTitle>Your entry, on the record.</DialogTitle><DialogDescription>Confirmed on Solana. Keep the details of your decision.</DialogDescription>{receipt&&<><div className="review-amount">{receipt.tokens.toLocaleString(undefined,{maximumFractionDigits:6})}<span>{receipt.symbol} tokens received</span></div><dl className="review-details"><div><dt>Spent</dt><dd>{receipt.amount.toFixed(6)} USDC</dd></div><div><dt>Effective entry</dt><dd>{money(receipt.entryPrice)} / token</dd></div><div><dt>Confirmed at</dt><dd>{new Date(receipt.time).toLocaleString()}</dd></div></dl><a className="secondary-button" href={'https://solscan.io/tx/'+receipt.signature} target="_blank" rel="noreferrer">View transaction <ExternalLink size={16}/></a><button className="primary-button full" onClick={share}>{copied?'Receipt copied':'Copy shareable receipt'}{copied?<Check size={16}/>:<Copy size={16}/>}</button></>}</DialogContent></Dialog>
  {receipt&&!receiptOpen&&<button className="receipt-fab" onClick={()=>setReceiptOpen(true)}><ReceiptText size={17}/>Your latest receipt</button>}
 </div>
}
